BoatRenting/Models/RentBoat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BoatRenting.Models
{
    public class RentBoat
    {
        public long BoatId { get; set; }
        public string BoatName { get; set; }
        public string BoatColor { get; set; }
        public string RentRate { get; set; }
        public string Status { get; set; }
        public string IsRented { get; set; }
        public string RentedOn { get; set; }
        public string AvailableTime { get; set; }
        public string RentTo { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? RentedFor { get; set; }
    }
}

BoatRenting/Controllers/BoatRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoatRenting.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BoatRenting.Controllers
{
    public class BoatRegistrationController : Controller
    {
        private readonly BoatRentContext _context;
        private readonly IStaticValues _staticValues;
        private string _UserId;
        const string UserId = "UserId";
        public BoatRegistrationController(BoatRentContext context,IStaticValues staticValues)
        {
            _context = context;
            _staticValues = staticValues;
        }
        public IActionResult Index()
        {


            _UserId = HttpContext.Session.GetString(UserId);
            if (!String.IsNullOrEmpty(_UserId))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }


        }
        [HttpPost]
        public async Task<IActionResult> Register(BoatRegistrationModel BoatData)
        {
            try
            {
                DateTime currDate = DateTime.Now;
                DateTime CurDateTime = DateTime.Now;
                BoatMaster objBoatMaster = new BoatMaster();
                objBoatMaster.BoatName = BoatData.BoatName;
                objBoatMaster.RentRate = BoatData.BoatRent;
                objBoatMaster.BoatColor = BoatData.BoatColor;
                objBoatMaster.CreatedBy = Convert.ToInt64(HttpContext.Session.GetString(UserId));
                objBoatMaster.CreationDate = currDate;
                objBoatMaster.IsRented = StaticValues.BoatCurentlyAvailable;
                objBoatMaster.IsActive = StaticValues.Active;
                _context.BoatMaster.Add(objBoatMaster);
                await _context.SaveChangesAsync();
                TempData["BoatID"] = " having Boat Id:"+ objBoatMaster.BoatId.ToString();
                TempData["SuccessMessage"] = "Record Saved Successfully";
                return RedirectToAction("Index", "RentBoat");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }


        }
    }
}

BoatRenting/Controllers/RentBoatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoatRenting.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoatRenting.Controllers
{
    public class RentBoatController : Controller
    {
        private readonly BoatRentContext _context;
        private string _UserId;
        const string UserId = "UserId";
        private readonly IStaticValues _staticValues;
        public RentBoatController(BoatRentContext context,IStaticValues staticValues)
        {
            _context = context;
            _staticValues = staticValues;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                _UserId = HttpContext.Session.GetString(UserId);
                if (!String.IsNullOrEmpty(_UserId))
                {
                    var objBoatLst = _context.BoatMaster.Select(x => new RentBoat
                    {
                        BoatId = x.BoatId,
                        BoatName = x.BoatName,
                        BoatColor = x.BoatColor,
                        RentRate = x.RentRate.ToString("0.00"),
                        IsRented = x.IsRented,
                        AvailableTime = "",
                        Status = (x.IsActive == StaticValues.Active) ? "Active" : "Deactive"
                    }).ToListAsync();
                    objBoatLst.Result.ForEach(x =>
                    {
                        if (x.IsRented == StaticValues.BoatCurentlyRented)
                        {
                            var objRentData = _context.RentMaster.Where(z => z.BoatId == x.BoatId && z.IsActive == StaticValues.Active).FirstOrDefault();
                            if (objRentData.RentFor.Value > 0)
                            {
                                var rentedOn = objRentData.RentOn;
                                DateTime TimeUptoRentedFor = rentedOn.AddHours((double)objRentData.RentFor.Value);
                                TimeSpan TimeRemaining = TimeUptoRentedFor - DateTime.Now;
                                x.AvailableTime = "Available after ";
                                if (TimeRemaining.Hours > 0)
                                {
                                    x.AvailableTime = x.AvailableTime + TimeRemaining.Hours + " Hours ";
                                }
                                if (TimeRemaining.Minutes > 0)
                                {
                                    x.AvailableTime = x.AvailableTime + TimeRemaining.Minutes + " Minutes";
                                }
                                else
                                {
                                    x.AvailableTime = "Soon Available!";
                                }
                            }
                            else
                            {
                                x.AvailableTime = "Availablity time not available!";
                            }
                        }
                        else
                        {
                            if (x.Status == "Active")
                            {
                                x.AvailableTime = "Currently Available!";
                            }
                            else
                            {
                                x.AvailableTime = "Un-Available!";
                            }

                        }
                    });

                    return View(await objBoatLst);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
            

        }

        public async Task<IActionResult> Active(long? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("No Record Found!");
                }

                var boatMaster = await _context.BoatMaster.Where(x => x.BoatId == (long)id).FirstOrDefaultAsync(); ;
                if (boatMaster == null)
                {
                    throw new Exception("No Record Found!");
                }
                else
                {
                    boatMaster.IsActive = StaticValues.Active;
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
           

        }
        public async Task<IActionResult> DeActive(long? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("No Record Found!");
                }

                var boatMaster = await _context.BoatMaster.Where(x => x.BoatId == (long)id).FirstOrDefaultAsync();
                if (boatMaster == null)
                {
                    throw new Exception("No Record Found!");
                }
                else
                {
                    boatMaster.IsActive = StaticValues.DeActive;
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            

        }

        public async Task<IActionResult> Rent(long? id)
        {
            var BoatDetails = await _context.BoatMaster.Where(x => x.BoatId == id).Select(x => new RentBoat
            {
                BoatId = x.BoatId,
                BoatName = x.BoatName,
                RentRate = x.RentRate.ToString("0.00"),
                BoatColor = x.BoatColor
            }).FirstOrDefaultAsync();

            return View(BoatDetails);
        }
        [HttpPost]
        public async Task<IActionResult> RentTheBoat(RentBoat objRequest)
        {
            try
            {
                DateTime CurDateTime = DateTime.Now;
                RentMaster objRentMaster = new RentMaster();
                objRentMaster.BoatId = objRequest.BoatId;
                objRentMaster.RentTo = objRequest.RentTo;
                objRentMaster.RentOn = CurDateTime;
                objRentMaster.CreationDate = CurDateTime;
                objRentMaster.RentFor = objRequest.RentedFor;
                objRentMaster.IsActive = StaticValues.Active;
                objRentMaster.CreatedBy = Convert.ToInt64(HttpContext.Session.GetString(UserId));

                var objBoatMaster = _context.BoatMaster.Where(x => x.BoatId == objRequest.BoatId).FirstOrDefault();

                objBoatMaster.IsRented = StaticValues.BoatCurentlyRented;
                _context.Add(objRentMaster);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Boat Rented Successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }

        }
        [HttpPost]
        public async Task<IActionResult> Details(long? id)
        {
            var BoatDetails = await _context.RentMaster.Where(x => x.BoatId == id && x.IsActive == StaticValues.Active).Select(x => new RentBoat
            {
                BoatId = x.BoatId,
                BoatName = x.Boat.BoatName,
                RentRate = x.Boat.RentRate.ToString("0.00"),
                BoatColor = x.Boat.BoatColor,
                RentTo = x.RentTo,
                RentedOn = x.RentOn.ToString("dd-MMM-yyyy hh:mm tt"),
                RentedFor=x.RentFor
            }).FirstOrDefaultAsync();
            return View(BoatDetails);
        }

        public async Task<IActionResult> CreateBill(long? id)
        {
            try
            {
                var objRentDetals = await _context.RentMaster.Where(x => x.BoatId == id && x.IsActive == StaticValues.Active).Select(x => new RentBoat
                {
                    BoatId = x.BoatId,
                    BoatName = x.Boat.BoatName,
                    RentRate = x.Boat.RentRate.ToString("0.00"),
                    BoatColor = x.Boat.BoatColor,
                    RentTo = x.RentTo,
                    RentedOn = x.RentOn.ToString("dd-MMM-yyyy hh:mm tt"),
                    RentedFor = x.RentFor,
                    TotalAmount = _staticValues.CalculateAmount(x.RentOn, x.Boat.RentRate)
                }).FirstOrDefaultAsync();
                return View(objRentDetals);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            
        }

        public async Task<IActionResult> CreateBilling(RentBoat objRequest)
        {
            try
            {
                var objBoatRent = _context.RentMaster.Where(x => x.BoatId == objRequest.BoatId && x.IsActive == StaticValues.Active).FirstOrDefaultAsync();

                //Update Status
                objBoatRent.Result.IsActive = StaticValues.DeActive;

                var objBoatMaster = _context.BoatMaster.Where(x => x.BoatId == objRequest.BoatId).FirstOrDefault();
                objBoatMaster.IsRented = StaticValues.BoatCurentlyAvailable;

                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Boat Collected Successfully";
                return RedirectToAction(nameof(Index));
            }

BoatRenting/Views/RentBoat/CreateBill.cshtml
@{
    ViewData["Title"] = "CreateBill";
}

<h1>Create Bill</h1>

<div class="row">
    <div class="col-md-12">
        <form asp-action="CreateBilling">
            <div class="form-group">
                <label for="BoatId" class="control-label">Boat Id</label>
                <input name="BoatId" class="form-control" value="@Model.BoatId" readonly />

            </div>
            <div class="form-group">
                <label for="BoatName" class="control-label">Boat Name</label>
                <input name="BoatName" class="form-control" value="@Model.BoatName" readonly />
            </div>
            <div class="form-group">
                <label for="BoatColor" class="control-label"></label>
                <input name="BoatColor" class="form-control" value="@Model.BoatColor" readonly />
            </div>
            <div class="form-group">
                <label for="RentRate" class="control-label">Rent Rate (Hourly)</label>
                <input name="RentRate" class="form-control" readonly value="@Model.RentRate" />
            </div>
            <div class="form-group">
                <label for="RentTo" class="control-label">Rent To</label>
                <input name="RentTo" type="text" class="form-control" value="@Model.RentTo" readonly required />
            </div>
            <div class="form-group">
                <label for="RentedFor" class="control-label">Rent Time (Hours)</label>
                <input name="RentedFor" type="number" step="any" value="@Model.RentedFor" readonly class="form-control" />
            </div>
            <div class="form-group">
                <label for="RentedOn" class="control-label">Rented On</label>
                <input name="RentedOn" type="text" value="@Model.RentedOn" readonly class="form-control" />
            </div>
            
            <div class="form-group">
                <label for="RentedOn" class="control-label">Total Amount</label>
                <input name="TotalAmount" type="text" value="@Model.TotalAmount"  readonly class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create Bill" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BoatRenting/Views/RentBoat/Details.cshtml
@model BoatRenting.Models.RentBoat
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div class="row">
    <div class="col-md-12">
        <form asp-action="RentTheBoat">
            <div class="form-group">
                <label for="BoatId" class="control-label">Boat Id</label>
                <input name="BoatId" class="form-control" value="@Model.BoatId" readonly />

            </div>
            <div class="form-group">
                <label for="BoatName" class="control-label">Boat Name</label>
                <input name="BoatName" class="form-control" value="@Model.BoatName" readonly />
            </div>
            <div class="form-group">
                <label for="BoatColor" class="control-label"></label>
                <input name="BoatColor" class="form-control" value="@Model.BoatColor" readonly />
            </div>
            <div class="form-group">
                <label for="RentRate" class="control-label">Rent Rate (Hourly)</label>
                <input name="RentRate" class="form-control" readonly value="@Model.RentRate" />
            </div>
            <div class="form-group">
                <label for="RentTo" class="control-label">Rent To</label>
                <input name="RentTo" type="text" class="form-control" value="@Model.RentTo" readonly required />
            </div>
            <div class="form-group">
                <label for="RentedFor" class="control-label">Rent Time (Hours)</label>
                <input name="RentedFor" type="number" step="any" value="@Model.RentedFor" readonly class="form-control" />
            </div>
            <div class="form-group">
                <label for="RentedOn" class="control-label">Rented On</label>
                <input name="RentedOn" type="text" value="@Model.RentedOn" readonly class="form-control" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BoatRenting/Views/RentBoat/Index.cshtml
@model IEnumerable<BoatRenting.Models.RentBoat>
@{
    ViewData["Title"] = "Rent Boat";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1 class="text-center">Rent Boat</h1>

<div class="form-group">
    <label id="MessageAlert" style="color:green;font-weight:bolder" class="Message-Alert control-label">@TempData["SuccessMessage"] @TempData["BoatID"]</label>

    <label id="MessageAlert" style="color:red;font-weight:bolder" class="Message-Alert control-label">@TempData["ErrorMessage"]</label>
</div>
<div class="form-group">
    @using (Html.BeginForm("Index", "BoatRegistration", null, FormMethod.Post))
    {
        <button type="submit" style="margin:5px;" class="btn btn-primary">Register New Boat</button>
    }
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Boat Id
            </th>
            <th>
                Boat Name
            </th>
            <th>
                Boat Color
            </th>
            <th>
                Rent Rate (Hourly)
            </th>
            <th>
                Status
            </th>
            <th>
                Available Time
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BoatId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BoatName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BoatColor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RentRate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AvailableTime)
                </td>

                <td style="display:flex">
                    @*<a asp-action="Rent" asp-route-id="@item.BoatId">Rent</a>*@
                    @using (Html.BeginForm("Rent", "RentBoat", new { id = item.BoatId }, FormMethod.Post))
                    {
                        <button type="submit" style="margin:5px;display:@((item.IsRented == "N" && item.Status == "Active") ? "block" : "none")" class="btn btn-primary">Rent</button>
                    }
                    @using (Html.BeginForm("Details", "RentBoat", new { id = item.BoatId }, FormMethod.Post))
                    {
                        <button type="submit" style="margin:5px;display:@((item.IsRented == "Y") ? "block" : "none")" class="btn btn-primary">Details</button>
                    }
                    @using (Html.BeginForm("CreateBill", "RentBoat", new { id = item.BoatId }, FormMethod.Post))
                    {
                        <button type="submit" style="margin:5px;display:@((item.IsRented == "Y") ? "block" : "none")" class="btn btn-primary">Create Bill</button>
                    }
                    @using (Html.BeginForm("Active", "RentBoat", new { id = item.BoatId }, FormMethod.Post))
                    {
                        <button type="submit" class="btn btn-success" style="margin: 5px; display:@((item.Status == "Active" || item.IsRented=="Y") ? "none" : "block")">Active</button>
                    }
                    @using (Html.BeginForm("DeActive", "RentBoat", new { id = item.BoatId }, FormMethod.Post))
                    {
                        <button type="submit" class="btn btn-danger" style="margin: 5px; display:@((item.Status == "Active" && item.IsRented=="N") ? "block" : "none")">De-Active</button>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    setTimeout(function () {
        $("#MessageAlert").fadeOut(100000);
    }, 3000);
</script>

BoatRenting/Views/RentBoat/Rent.cshtml
@model BoatRenting.Models.RentBoat
@{
    ViewData["Title"] = "Rent";
}

<h1>Rent Boat</h1>

<div class="row">
    <div class="col-md-12">
        <form asp-action="RentTheBoat">
            <div class="form-group">
                <label for="BoatId" class="control-label">Boat Id</label>
                <input name="BoatId" class="form-control" value="@Model.BoatId" readonly />

            </div>
            <div class="form-group">
                <label for="BoatName" class="control-label">Boat Name</label>
                <input name="BoatName" class="form-control" value="@Model.BoatName" readonly />
            </div>
            <div class="form-group">
                <label for="BoatColor" class="control-label"></label>
                <input name="BoatColor" class="form-control" value="@Model.BoatColor" readonly />
            </div>
            <div class="form-group">
                <label for="RentRate" class="control-label">Rent Rate (Hourly)</label>
                <input name="RentRate" class="form-control" readonly value="@Model.RentRate" />
            </div>
            <div class="form-group">
                <label for="RentTo" class="control-label">Rent To</label>
                <input name="RentTo" type="text"  class="form-control" required />
            </div>
            <div class="form-group">
                <label for="RentedFor" class="control-label">Rent Time (Hours)</label>
                <input name="RentedFor" type="number" step="any" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Rent" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>